name: Test Bot

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: [3.8, 3.9, '3.10', '3.11']
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Lint with flake8
      run: |
        pip install flake8
        # Stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # Exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Check environment template
      run: |
        # Verify .env.template exists and has required variables
        test -f .env.template
        grep -q "DISCORD_TOKEN" .env.template
        grep -q "CRCON_API_KEY" .env.template
    
    - name: Test bot import
      run: |
        # Create minimal .env for import test
        echo "DISCORD_TOKEN=test_token" > .env
        echo "CRCON_API_KEY=test_key" >> .env
        # Test that the bot file can be imported without errors
        python -c "import enhanced_discord_bot; print('Bot imports successfully')"
